services:
  app:
    container_name: data-ingestor-python
    env_file:
      - ./.env
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      DB_ORACLE_USER: ${DB_ORACLE_USER}
      DB_ORACLE_PASSWORD: ${DB_ORACLE_PASSWORD}
      DB_ORACLE_DSN: ${DB_ORACLE_DSN}
      MINIO_URL: ${MINIO_URL}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      API_LOGIN_ANALYTICS: ${API_LOGIN_ANALYTICS}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    command: "python app/server.py"
    ports:
      - "8001:8001"
    restart: always
    volumes:
      - /home/opc/keys/:/keys/
      - /var/www/api-sql-reports/data-ingestor-python/database/:/opt/database
    network_mode: "host"
