apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqllite-pvc
  namespace: api-sql-reports
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.25Gi
  storageClassName: nas-001
  volumeMode: Filesystem